services:
  k3s-server:
    image: rancher/k3s:latest
    privileged: true
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
    ports:
      - "6443:6443"  # Kubernetes API port
      - "8089:32000"  # Map 80 to 32000 (home assistant node port)

    volumes:
      - k3s-server-data:/var/lib/rancher/k3s
      - ./output:/output
      - k3s-shared:/var/lib/rancher/k3s/server
    command: ["server", "--tls-san", "k3s-server"]
  k3s-agent:
    image: rancher/k3s:latest
    privileged: true
    environment:
      - K3S_URL=https://k3s-server:6443
      - K3S_TOKEN_FILE=/var/lib/rancher/k3s/server/node-token
    depends_on:
      - k3s-server
    volumes:
      - k3s-agent-data:/var/lib/rancher/k3s
      - k3s-shared:/var/lib/rancher/k3s/server
    command: ["agent"]

volumes:
  k3s-server-data:
  k3s-agent-data:
  k3s-shared:

