# MongoDB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: home-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: home-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "admin"  # Replace with MongoDB username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"  # Replace with MongoDB password
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongodb"  # MongoDB service name
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: home-core
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32003  # Customize to an available port
  selector:
    app: mongo-express

