apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: home-core
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "kubernetes-nodes"
        kubernetes_sd_configs:
          - role: node

      - job_name: "kubernetes-pods"
        kubernetes_sd_configs:
          - role: pod

---
# Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: home-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus/
              name: prometheus-config
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-server-conf

---

# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: home-core
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30900
  selector:
    app: prometheus

